name: Android (Maestro Cloud)

on: [push, pull_request]


jobs:
  run_android_e2e:
    timeout-minutes: 45
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        api-level: [33]
        # ^^^ from: https://cloud.mobile.dev/reference/device-configuration#android

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: mobile-dev-inc/action-maestro-cloud@v1
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          workspace: android/
          app-binary-id: 180a59b33ea84d0576ce1310fdb5b1557d712cd5
          android-api-level: ${{ matrix.api-level }}