name: Android Instrumentation Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  android_test:
     name: Running Android Tests
     runs-on: macos-13
     continue-on-error: true
     steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - uses: dniHze/maestro-test-action@v1

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
           api-level: 26
           target: default
           arch: x86_64
           profile: Nexus 4
           script: |
            adb kill-server
            adb start-server
            maestro test maestro/android/login/loginCapivara.yaml --format=junit --output=report.xml --no-ansi